f01_totalBasicBlocks: 26
f02_oneSuccessor: 14
f03_twoSuccessor: 10
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 15
f06_twoPredecessor: 8
f07_greaterTwoPredecessor: 2
f08_onePredSuc: 10
f09_onePred_twoSuc: 3
f10_twoPred_oneSuc: 2
f11_twoPredSuc: 6
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 26
f14_instructionInterval: 0
f15_instructionGreater500: 0
f16_numOfEdges: 37
f17_numOfCriticalEdges: 8
f18_abnormalEdge: 0
f19_directCalls: 5
f20_condBranch: 10
f21_assigmentInstructions: 46
f22_uncondBranch: 14
f23_numOfIntOperations: 0
f24_numOfFloatOperations: 0
f25_numInstructions: 76
f26_instructionAverage: 2.923077
f27_averagePhi: 0.07692308
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 24
f30_blockPhiIntervalNodes: 26
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 2
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 3
f38_addresVar: 3
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 2
f42_oneOperandConst: 0
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 5
f47_constInt0: 15
f48_constInt32bits: 18
f49_constInt1: 3
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 53
f52_defUseCounter: 4
f53_refLocalVariable: 44
f54_refExterVariable: 3
f55_localPtrVar: 16
f56_staticPtrVar: 0
