f01_totalBasicBlocks: 103
f02_oneSuccessor: 54
f03_twoSuccessor: 47
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 69
f06_twoPredecessor: 14
f07_greaterTwoPredecessor: 19
f08_onePredSuc: 47
f09_onePred_twoSuc: 21
f10_twoPred_oneSuc: 0
f11_twoPredSuc: 14
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 96
f14_instructionInterval: 7
f15_instructionGreater500: 0
f16_numOfEdges: 155
f17_numOfCriticalEdges: 41
f18_abnormalEdge: 0
f19_directCalls: 0
f20_condBranch: 47
f21_assigmentInstructions: 572
f22_uncondBranch: 54
f23_numOfIntOperations: 9
f24_numOfFloatOperations: 0
f25_numInstructions: 776
f26_instructionAverage: 7.53398
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 103
f30_blockPhiIntervalNodes: 103
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 72
f38_addresVar: 72
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 1
f42_oneOperandConst: 9
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 0
f47_constInt0: 288
f48_constInt32bits: 490
f49_constInt1: 63
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 667
f52_defUseCounter: 151
f53_refLocalVariable: 571
f54_refExterVariable: 9
f55_localPtrVar: 469
f56_staticPtrVar: 142
