f01_totalBasicBlocks: 22
f02_oneSuccessor: 10
f03_twoSuccessor: 11
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 14
f06_twoPredecessor: 4
f07_greaterTwoPredecessor: 3
f08_onePredSuc: 5
f09_onePred_twoSuc: 9
f10_twoPred_oneSuc: 3
f11_twoPredSuc: 1
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 22
f14_instructionInterval: 0
f15_instructionGreater500: 0
f16_numOfEdges: 32
f17_numOfCriticalEdges: 9
f18_abnormalEdge: 0
f19_directCalls: 2
f20_condBranch: 11
f21_assigmentInstructions: 29
f22_uncondBranch: 10
f23_numOfIntOperations: 0
f24_numOfFloatOperations: 0
f25_numInstructions: 59
f26_instructionAverage: 2.681818
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 22
f30_blockPhiIntervalNodes: 22
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 0
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 0
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 2
f47_constInt0: 14
f48_constInt32bits: 16
f49_constInt1: 2
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 38
f52_defUseCounter: 8
f53_refLocalVariable: 29
f54_refExterVariable: 7
f55_localPtrVar: 4
f56_staticPtrVar: 0
