f01_totalBasicBlocks: 36
f02_oneSuccessor: 25
f03_twoSuccessor: 9
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 24
f06_twoPredecessor: 11
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 19
f09_onePred_twoSuc: 3
f10_twoPred_oneSuc: 5
f11_twoPredSuc: 6
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 35
f14_instructionInterval: 1
f15_instructionGreater500: 0
f16_numOfEdges: 46
f17_numOfCriticalEdges: 3
f18_abnormalEdge: 0
f19_directCalls: 4
f20_condBranch: 9
f21_assigmentInstructions: 110
f22_uncondBranch: 25
f23_numOfIntOperations: 6
f24_numOfFloatOperations: 0
f25_numInstructions: 169
f26_instructionAverage: 4.694445
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 36
f30_blockPhiIntervalNodes: 36
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 5
f38_addresVar: 2
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 6
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 4
f47_constInt0: 23
f48_constInt32bits: 50
f49_constInt1: 9
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 138
f52_defUseCounter: 18
f53_refLocalVariable: 107
f54_refExterVariable: 4
f55_localPtrVar: 56
f56_staticPtrVar: 11
