f01_totalBasicBlocks: 33
f02_oneSuccessor: 18
f03_twoSuccessor: 14
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 18
f06_twoPredecessor: 14
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 12
f09_onePred_twoSuc: 6
f10_twoPred_oneSuc: 6
f11_twoPredSuc: 7
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 31
f14_instructionInterval: 2
f15_instructionGreater500: 0
f16_numOfEdges: 46
f17_numOfCriticalEdges: 11
f18_abnormalEdge: 0
f19_directCalls: 7
f20_condBranch: 14
f21_assigmentInstructions: 117
f22_uncondBranch: 18
f23_numOfIntOperations: 3
f24_numOfFloatOperations: 0
f25_numInstructions: 169
f26_instructionAverage: 5.121212
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 33
f30_blockPhiIntervalNodes: 33
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 15
f38_addresVar: 15
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 1
f42_oneOperandConst: 3
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 7
f47_constInt0: 33
f48_constInt32bits: 56
f49_constInt1: 16
f50_constInt64bits: 1
f51_numRefeOfLocalVar: 124
f52_defUseCounter: 41
f53_refLocalVariable: 109
f54_refExterVariable: 13
f55_localPtrVar: 76
f56_staticPtrVar: 34
