f01_totalBasicBlocks: 11
f02_oneSuccessor: 5
f03_twoSuccessor: 5
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 5
f06_twoPredecessor: 5
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 5
f09_onePred_twoSuc: 0
f10_twoPred_oneSuc: 0
f11_twoPredSuc: 4
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 10
f14_instructionInterval: 1
f15_instructionGreater500: 0
f16_numOfEdges: 15
f17_numOfCriticalEdges: 5
f18_abnormalEdge: 0
f19_directCalls: 3
f20_condBranch: 5
f21_assigmentInstructions: 44
f22_uncondBranch: 5
f23_numOfIntOperations: 2
f24_numOfFloatOperations: 0
f25_numInstructions: 63
f26_instructionAverage: 5.727273
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 11
f30_blockPhiIntervalNodes: 11
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 2
f38_addresVar: 2
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 0
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 3
f47_constInt0: 16
f48_constInt32bits: 16
f49_constInt1: 0
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 53
f52_defUseCounter: 9
f53_refLocalVariable: 43
f54_refExterVariable: 7
f55_localPtrVar: 19
f56_staticPtrVar: 0
