f01_totalBasicBlocks: 14
f02_oneSuccessor: 7
f03_twoSuccessor: 6
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 8
f06_twoPredecessor: 4
f07_greaterTwoPredecessor: 1
f08_onePredSuc: 6
f09_onePred_twoSuc: 2
f10_twoPred_oneSuc: 1
f11_twoPredSuc: 2
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 14
f14_instructionInterval: 0
f15_instructionGreater500: 0
f16_numOfEdges: 19
f17_numOfCriticalEdges: 4
f18_abnormalEdge: 0
f19_directCalls: 2
f20_condBranch: 6
f21_assigmentInstructions: 49
f22_uncondBranch: 7
f23_numOfIntOperations: 0
f24_numOfFloatOperations: 0
f25_numInstructions: 73
f26_instructionAverage: 5.214286
f27_averagePhi: 0.07142857
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 13
f30_blockPhiIntervalNodes: 14
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 1
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 3
f38_addresVar: 2
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 1
f42_oneOperandConst: 0
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 2
f47_constInt0: 19
f48_constInt32bits: 24
f49_constInt1: 1
f50_constInt64bits: 1
f51_numRefeOfLocalVar: 55
f52_defUseCounter: 15
f53_refLocalVariable: 49
f54_refExterVariable: 5
f55_localPtrVar: 22
f56_staticPtrVar: 11
