clang:
  O0:
    goal: 875.0
    seq:
    - -O0
  O1:
    goal: 470.0
    seq:
    - -O1
  O2:
    goal: 560.0
    seq:
    - -O2
  O3:
    goal: 560.0
    seq:
    - -O3
  Os:
    goal: 461.0
    seq:
    - -Os
  Oz:
    goal: 457.0
    seq:
    - -Oz
opt:
  O0:
    goal: 875.0
    seq:
    - -O0
  O1:
    goal: 540.0
    seq:
    - -O1
  O2:
    goal: 531.0
    seq:
    - -O2
  O3:
    goal: 531.0
    seq:
    - -O3
  Os:
    goal: 531.0
    seq:
    - -Os
  Oz:
    goal: 428.0
    seq:
    - -Oz
