clang:
  O0:
    goal: 320.0
    seq:
    - -O0
  O1:
    goal: 188.0
    seq:
    - -O1
  O2:
    goal: 177.0
    seq:
    - -O2
  O3:
    goal: 177.0
    seq:
    - -O3
  Os:
    goal: 177.0
    seq:
    - -Os
  Oz:
    goal: 177.0
    seq:
    - -Oz
opt:
  O0:
    goal: 320.0
    seq:
    - -O0
  O1:
    goal: 189.0
    seq:
    - -O1
  O2:
    goal: 178.0
    seq:
    - -O2
  O3:
    goal: 178.0
    seq:
    - -O3
  Os:
    goal: 178.0
    seq:
    - -Os
  Oz:
    goal: 178.0
    seq:
    - -Oz
