clang:
  O0:
    goal: 433.0
    seq:
    - -O0
  O1:
    goal: 262.0
    seq:
    - -O1
  O2:
    goal: 250.0
    seq:
    - -O2
  O3:
    goal: 250.0
    seq:
    - -O3
  Os:
    goal: 250.0
    seq:
    - -Os
  Oz:
    goal: 248.0
    seq:
    - -Oz
opt:
  O0:
    goal: 433.0
    seq:
    - -O0
  O1:
    goal: 264.0
    seq:
    - -O1
  O2:
    goal: 255.0
    seq:
    - -O2
  O3:
    goal: 255.0
    seq:
    - -O3
  Os:
    goal: 255.0
    seq:
    - -Os
  Oz:
    goal: 250.0
    seq:
    - -Oz
