clang:
  O0:
    goal: 932.0
    seq:
    - -O0
  O1:
    goal: 317.0
    seq:
    - -O1
  O2:
    goal: 335.0
    seq:
    - -O2
  O3:
    goal: 335.0
    seq:
    - -O3
  Os:
    goal: 310.0
    seq:
    - -Os
  Oz:
    goal: 306.0
    seq:
    - -Oz
opt:
  O0:
    goal: 932.0
    seq:
    - -O0
  O1:
    goal: 324.0
    seq:
    - -O1
  O2:
    goal: 344.0
    seq:
    - -O2
  O3:
    goal: 344.0
    seq:
    - -O3
  Os:
    goal: 344.0
    seq:
    - -Os
  Oz:
    goal: 315.0
    seq:
    - -Oz
