clang:
  O0:
    goal: 531.0
    seq:
    - -O0
  O1:
    goal: 357.0
    seq:
    - -O1
  O2:
    goal: 483.0
    seq:
    - -O2
  O3:
    goal: 483.0
    seq:
    - -O3
  Os:
    goal: 358.0
    seq:
    - -Os
  Oz:
    goal: 360.0
    seq:
    - -Oz
opt:
  O0:
    goal: 531.0
    seq:
    - -O0
  O1:
    goal: 482.0
    seq:
    - -O1
  O2:
    goal: 483.0
    seq:
    - -O2
  O3:
    goal: 483.0
    seq:
    - -O3
  Os:
    goal: 483.0
    seq:
    - -Os
  Oz:
    goal: 373.0
    seq:
    - -Oz
