clang:
  O0:
    goal: 735.0
    seq:
    - -O0
  O1:
    goal: 554.0
    seq:
    - -O1
  O2:
    goal: 503.0
    seq:
    - -O2
  O3:
    goal: 503.0
    seq:
    - -O3
  Os:
    goal: 503.0
    seq:
    - -Os
  Oz:
    goal: 496.0
    seq:
    - -Oz
opt:
  O0:
    goal: 735.0
    seq:
    - -O0
  O1:
    goal: 542.0
    seq:
    - -O1
  O2:
    goal: 500.0
    seq:
    - -O2
  O3:
    goal: 500.0
    seq:
    - -O3
  Os:
    goal: 500.0
    seq:
    - -Os
  Oz:
    goal: 495.0
    seq:
    - -Oz
