clang:
  O0:
    goal: 312.0
    seq:
    - -O0
  O1:
    goal: 126.0
    seq:
    - -O1
  O2:
    goal: 125.0
    seq:
    - -O2
  O3:
    goal: 125.0
    seq:
    - -O3
  Os:
    goal: 125.0
    seq:
    - -Os
  Oz:
    goal: 125.0
    seq:
    - -Oz
opt:
  O0:
    goal: 312.0
    seq:
    - -O0
  O1:
    goal: 143.0
    seq:
    - -O1
  O2:
    goal: 142.0
    seq:
    - -O2
  O3:
    goal: 142.0
    seq:
    - -O3
  Os:
    goal: 142.0
    seq:
    - -Os
  Oz:
    goal: 142.0
    seq:
    - -Oz
