clang:
  O0:
    goal: 1107.0
    seq:
    - -O0
  O1:
    goal: 524.0
    seq:
    - -O1
  O2:
    goal: 556.0
    seq:
    - -O2
  O3:
    goal: 556.0
    seq:
    - -O3
  Os:
    goal: 556.0
    seq:
    - -Os
  Oz:
    goal: 545.0
    seq:
    - -Oz
opt:
  O0:
    goal: 1107.0
    seq:
    - -O0
  O1:
    goal: 581.0
    seq:
    - -O1
  O2:
    goal: 583.0
    seq:
    - -O2
  O3:
    goal: 583.0
    seq:
    - -O3
  Os:
    goal: 583.0
    seq:
    - -Os
  Oz:
    goal: 579.0
    seq:
    - -Oz
