clang:
  O0:
    goal: 1066.0
    seq:
    - -O0
  O1:
    goal: 652.0
    seq:
    - -O1
  O2:
    goal: 650.0
    seq:
    - -O2
  O3:
    goal: 650.0
    seq:
    - -O3
  Os:
    goal: 650.0
    seq:
    - -Os
  Oz:
    goal: 646.0
    seq:
    - -Oz
opt:
  O0:
    goal: 1066.0
    seq:
    - -O0
  O1:
    goal: 646.0
    seq:
    - -O1
  O2:
    goal: 644.0
    seq:
    - -O2
  O3:
    goal: 644.0
    seq:
    - -O3
  Os:
    goal: 644.0
    seq:
    - -Os
  Oz:
    goal: 640.0
    seq:
    - -Oz
