clang:
  O0:
    goal: 549.0
    seq:
    - -O0
  O1:
    goal: 425.0
    seq:
    - -O1
  O2:
    goal: 425.0
    seq:
    - -O2
  O3:
    goal: 425.0
    seq:
    - -O3
  Os:
    goal: 425.0
    seq:
    - -Os
  Oz:
    goal: 425.0
    seq:
    - -Oz
opt:
  O0:
    goal: 549.0
    seq:
    - -O0
  O1:
    goal: 337.0
    seq:
    - -O1
  O2:
    goal: 337.0
    seq:
    - -O2
  O3:
    goal: 337.0
    seq:
    - -O3
  Os:
    goal: 337.0
    seq:
    - -Os
  Oz:
    goal: 337.0
    seq:
    - -Oz
