clang:
  O0:
    goal: 278.0
    seq:
    - -O0
  O1:
    goal: 143.0
    seq:
    - -O1
  O2:
    goal: 143.0
    seq:
    - -O2
  O3:
    goal: 143.0
    seq:
    - -O3
  Os:
    goal: 143.0
    seq:
    - -Os
  Oz:
    goal: 147.0
    seq:
    - -Oz
opt:
  O0:
    goal: 278.0
    seq:
    - -O0
  O1:
    goal: 143.0
    seq:
    - -O1
  O2:
    goal: 143.0
    seq:
    - -O2
  O3:
    goal: 143.0
    seq:
    - -O3
  Os:
    goal: 143.0
    seq:
    - -Os
  Oz:
    goal: 147.0
    seq:
    - -Oz
