clang:
  O0:
    goal: 1138.0
    seq:
    - -O0
  O1:
    goal: 606.0
    seq:
    - -O1
  O2:
    goal: 610.0
    seq:
    - -O2
  O3:
    goal: 610.0
    seq:
    - -O3
  Os:
    goal: 610.0
    seq:
    - -Os
  Oz:
    goal: 605.0
    seq:
    - -Oz
opt:
  O0:
    goal: 1138.0
    seq:
    - -O0
  O1:
    goal: 600.0
    seq:
    - -O1
  O2:
    goal: 604.0
    seq:
    - -O2
  O3:
    goal: 604.0
    seq:
    - -O3
  Os:
    goal: 604.0
    seq:
    - -Os
  Oz:
    goal: 599.0
    seq:
    - -Oz
