clang:
  O0:
    goal: 685.0
    seq:
    - -O0
  O1:
    goal: 427.0
    seq:
    - -O1
  O2:
    goal: 404.0
    seq:
    - -O2
  O3:
    goal: 404.0
    seq:
    - -O3
  Os:
    goal: 404.0
    seq:
    - -Os
  Oz:
    goal: 402.0
    seq:
    - -Oz
opt:
  O0:
    goal: 685.0
    seq:
    - -O0
  O1:
    goal: 419.0
    seq:
    - -O1
  O2:
    goal: 396.0
    seq:
    - -O2
  O3:
    goal: 396.0
    seq:
    - -O3
  Os:
    goal: 396.0
    seq:
    - -Os
  Oz:
    goal: 394.0
    seq:
    - -Oz
