clang:
  O0:
    goal: 443.0
    seq:
    - -O0
  O1:
    goal: 288.0
    seq:
    - -O1
  O2:
    goal: 284.0
    seq:
    - -O2
  O3:
    goal: 284.0
    seq:
    - -O3
  Os:
    goal: 284.0
    seq:
    - -Os
  Oz:
    goal: 289.0
    seq:
    - -Oz
opt:
  O0:
    goal: 443.0
    seq:
    - -O0
  O1:
    goal: 266.0
    seq:
    - -O1
  O2:
    goal: 265.0
    seq:
    - -O2
  O3:
    goal: 265.0
    seq:
    - -O3
  Os:
    goal: 265.0
    seq:
    - -Os
  Oz:
    goal: 282.0
    seq:
    - -Oz
