clang:
  O0:
    goal: 315.0
    seq:
    - -O0
  O1:
    goal: 201.0
    seq:
    - -O1
  O2:
    goal: 200.0
    seq:
    - -O2
  O3:
    goal: 200.0
    seq:
    - -O3
  Os:
    goal: 200.0
    seq:
    - -Os
  Oz:
    goal: 199.0
    seq:
    - -Oz
opt:
  O0:
    goal: 315.0
    seq:
    - -O0
  O1:
    goal: 198.0
    seq:
    - -O1
  O2:
    goal: 197.0
    seq:
    - -O2
  O3:
    goal: 197.0
    seq:
    - -O3
  Os:
    goal: 197.0
    seq:
    - -Os
  Oz:
    goal: 196.0
    seq:
    - -Oz
