clang:
  O0:
    goal: 295.0
    seq:
    - -O0
  O1:
    goal: 125.0
    seq:
    - -O1
  O2:
    goal: 119.0
    seq:
    - -O2
  O3:
    goal: 119.0
    seq:
    - -O3
  Os:
    goal: 119.0
    seq:
    - -Os
  Oz:
    goal: 116.0
    seq:
    - -Oz
opt:
  O0:
    goal: 295.0
    seq:
    - -O0
  O1:
    goal: 118.0
    seq:
    - -O1
  O2:
    goal: 113.0
    seq:
    - -O2
  O3:
    goal: 113.0
    seq:
    - -O3
  Os:
    goal: 113.0
    seq:
    - -Os
  Oz:
    goal: 110.0
    seq:
    - -Oz
