clang:
  O0:
    goal: 640.0
    seq:
    - -O0
  O1:
    goal: 449.0
    seq:
    - -O1
  O2:
    goal: 449.0
    seq:
    - -O2
  O3:
    goal: 449.0
    seq:
    - -O3
  Os:
    goal: 448.0
    seq:
    - -Os
  Oz:
    goal: 445.0
    seq:
    - -Oz
opt:
  O0:
    goal: 640.0
    seq:
    - -O0
  O1:
    goal: 449.0
    seq:
    - -O1
  O2:
    goal: 449.0
    seq:
    - -O2
  O3:
    goal: 449.0
    seq:
    - -O3
  Os:
    goal: 449.0
    seq:
    - -Os
  Oz:
    goal: 445.0
    seq:
    - -Oz
