clang:
  O0:
    goal: 348.0
    seq:
    - -O0
  O1:
    goal: 90.0
    seq:
    - -O1
  O2:
    goal: 90.0
    seq:
    - -O2
  O3:
    goal: 90.0
    seq:
    - -O3
  Os:
    goal: 90.0
    seq:
    - -Os
  Oz:
    goal: 90.0
    seq:
    - -Oz
opt:
  O0:
    goal: 348.0
    seq:
    - -O0
  O1:
    goal: 90.0
    seq:
    - -O1
  O2:
    goal: 90.0
    seq:
    - -O2
  O3:
    goal: 90.0
    seq:
    - -O3
  Os:
    goal: 90.0
    seq:
    - -Os
  Oz:
    goal: 90.0
    seq:
    - -Oz
