clang:
  O0:
    goal: 264.0
    seq:
    - -O0
  O1:
    goal: 133.0
    seq:
    - -O1
  O2:
    goal: 129.0
    seq:
    - -O2
  O3:
    goal: 133.0
    seq:
    - -O3
  Os:
    goal: 129.0
    seq:
    - -Os
  Oz:
    goal: 124.0
    seq:
    - -Oz
opt:
  O0:
    goal: 264.0
    seq:
    - -O0
  O1:
    goal: 133.0
    seq:
    - -O1
  O2:
    goal: 128.0
    seq:
    - -O2
  O3:
    goal: 132.0
    seq:
    - -O3
  Os:
    goal: 128.0
    seq:
    - -Os
  Oz:
    goal: 123.0
    seq:
    - -Oz
