clang:
  O0:
    goal: 437.0
    seq:
    - -O0
  O1:
    goal: 267.0
    seq:
    - -O1
  O2:
    goal: 259.0
    seq:
    - -O2
  O3:
    goal: 259.0
    seq:
    - -O3
  Os:
    goal: 259.0
    seq:
    - -Os
  Oz:
    goal: 259.0
    seq:
    - -Oz
opt:
  O0:
    goal: 437.0
    seq:
    - -O0
  O1:
    goal: 252.0
    seq:
    - -O1
  O2:
    goal: 244.0
    seq:
    - -O2
  O3:
    goal: 244.0
    seq:
    - -O3
  Os:
    goal: 244.0
    seq:
    - -Os
  Oz:
    goal: 244.0
    seq:
    - -Oz
