clang:
  O0:
    goal: 272.0
    seq:
    - -O0
  O1:
    goal: 175.0
    seq:
    - -O1
  O2:
    goal: 175.0
    seq:
    - -O2
  O3:
    goal: 175.0
    seq:
    - -O3
  Os:
    goal: 175.0
    seq:
    - -Os
  Oz:
    goal: 171.0
    seq:
    - -Oz
opt:
  O0:
    goal: 272.0
    seq:
    - -O0
  O1:
    goal: 173.0
    seq:
    - -O1
  O2:
    goal: 173.0
    seq:
    - -O2
  O3:
    goal: 173.0
    seq:
    - -O3
  Os:
    goal: 173.0
    seq:
    - -Os
  Oz:
    goal: 169.0
    seq:
    - -Oz
