clang:
  O0:
    goal: 313.0
    seq:
    - -O0
  O1:
    goal: 189.0
    seq:
    - -O1
  O2:
    goal: 182.0
    seq:
    - -O2
  O3:
    goal: 299.0
    seq:
    - -O3
  Os:
    goal: 182.0
    seq:
    - -Os
  Oz:
    goal: 180.0
    seq:
    - -Oz
opt:
  O0:
    goal: 313.0
    seq:
    - -O0
  O1:
    goal: 186.0
    seq:
    - -O1
  O2:
    goal: 179.0
    seq:
    - -O2
  O3:
    goal: 296.0
    seq:
    - -O3
  Os:
    goal: 179.0
    seq:
    - -Os
  Oz:
    goal: 177.0
    seq:
    - -Oz
