clang:
  O0:
    goal: 621.0
    seq:
    - -O0
  O1:
    goal: 375.0
    seq:
    - -O1
  O2:
    goal: 373.0
    seq:
    - -O2
  O3:
    goal: 373.0
    seq:
    - -O3
  Os:
    goal: 373.0
    seq:
    - -Os
  Oz:
    goal: 373.0
    seq:
    - -Oz
opt:
  O0:
    goal: 621.0
    seq:
    - -O0
  O1:
    goal: 369.0
    seq:
    - -O1
  O2:
    goal: 367.0
    seq:
    - -O2
  O3:
    goal: 367.0
    seq:
    - -O3
  Os:
    goal: 367.0
    seq:
    - -Os
  Oz:
    goal: 367.0
    seq:
    - -Oz
