clang:
  O0:
    goal: 514.0
    seq:
    - -O0
  O1:
    goal: 250.0
    seq:
    - -O1
  O2:
    goal: 242.0
    seq:
    - -O2
  O3:
    goal: 242.0
    seq:
    - -O3
  Os:
    goal: 242.0
    seq:
    - -Os
  Oz:
    goal: 236.0
    seq:
    - -Oz
opt:
  O0:
    goal: 514.0
    seq:
    - -O0
  O1:
    goal: 241.0
    seq:
    - -O1
  O2:
    goal: 239.0
    seq:
    - -O2
  O3:
    goal: 239.0
    seq:
    - -O3
  Os:
    goal: 239.0
    seq:
    - -Os
  Oz:
    goal: 233.0
    seq:
    - -Oz
