clang:
  O0:
    goal: 651.0
    seq:
    - -O0
  O1:
    goal: 415.0
    seq:
    - -O1
  O2:
    goal: 410.0
    seq:
    - -O2
  O3:
    goal: 410.0
    seq:
    - -O3
  Os:
    goal: 410.0
    seq:
    - -Os
  Oz:
    goal: 410.0
    seq:
    - -Oz
opt:
  O0:
    goal: 651.0
    seq:
    - -O0
  O1:
    goal: 407.0
    seq:
    - -O1
  O2:
    goal: 410.0
    seq:
    - -O2
  O3:
    goal: 410.0
    seq:
    - -O3
  Os:
    goal: 410.0
    seq:
    - -Os
  Oz:
    goal: 410.0
    seq:
    - -Oz
