clang:
  O0:
    goal: 169.0
    seq:
    - -O0
  O1:
    goal: 65.0
    seq:
    - -O1
  O2:
    goal: 33.0
    seq:
    - -O2
  O3:
    goal: 33.0
    seq:
    - -O3
  Os:
    goal: 42.0
    seq:
    - -Os
  Oz:
    goal: 84.0
    seq:
    - -Oz
opt:
  O0:
    goal: 169.0
    seq:
    - -O0
  O1:
    goal: 119.0
    seq:
    - -O1
  O2:
    goal: 104.0
    seq:
    - -O2
  O3:
    goal: 104.0
    seq:
    - -O3
  Os:
    goal: 104.0
    seq:
    - -Os
  Oz:
    goal: 134.0
    seq:
    - -Oz
