clang:
  O0:
    goal: 169.0
    seq:
    - -O0
  O1:
    goal: 154.0
    seq:
    - -O1
  O2:
    goal: 197.0
    seq:
    - -O2
  O3:
    goal: 197.0
    seq:
    - -O3
  Os:
    goal: 175.0
    seq:
    - -Os
  Oz:
    goal: 176.0
    seq:
    - -Oz
opt:
  O0:
    goal: 169.0
    seq:
    - -O0
  O1:
    goal: 172.0
    seq:
    - -O1
  O2:
    goal: 185.0
    seq:
    - -O2
  O3:
    goal: 185.0
    seq:
    - -O3
  Os:
    goal: 185.0
    seq:
    - -Os
  Oz:
    goal: 164.0
    seq:
    - -Oz
