clang:
  O0:
    goal: 776.0
    seq:
    - -O0
  O1:
    goal: 488.0
    seq:
    - -O1
  O2:
    goal: 676.0
    seq:
    - -O2
  O3:
    goal: 676.0
    seq:
    - -O3
  Os:
    goal: 453.0
    seq:
    - -Os
  Oz:
    goal: 459.0
    seq:
    - -Oz
opt:
  O0:
    goal: 776.0
    seq:
    - -O0
  O1:
    goal: 712.0
    seq:
    - -O1
  O2:
    goal: 676.0
    seq:
    - -O2
  O3:
    goal: 676.0
    seq:
    - -O3
  Os:
    goal: 676.0
    seq:
    - -Os
  Oz:
    goal: 459.0
    seq:
    - -Oz
