clang:
  O0:
    goal: 60.0
    seq:
    - -O0
  O1:
    goal: 37.0
    seq:
    - -O1
  O2:
    goal: 41.0
    seq:
    - -O2
  O3:
    goal: 41.0
    seq:
    - -O3
  Os:
    goal: 43.0
    seq:
    - -Os
  Oz:
    goal: 39.0
    seq:
    - -Oz
opt:
  O0:
    goal: 60.0
    seq:
    - -O0
  O1:
    goal: 53.0
    seq:
    - -O1
  O2:
    goal: 41.0
    seq:
    - -O2
  O3:
    goal: 41.0
    seq:
    - -O3
  Os:
    goal: 41.0
    seq:
    - -Os
  Oz:
    goal: 54.0
    seq:
    - -Oz
