f01_totalBasicBlocks: 21
f02_oneSuccessor: 12
f03_twoSuccessor: 6
f04_greaterTwoSuccessor: 2
f05_onePredecessor: 14
f06_twoPredecessor: 3
f07_greaterTwoPredecessor: 3
f08_onePredSuc: 10
f09_onePred_twoSuc: 2
f10_twoPred_oneSuc: 2
f11_twoPredSuc: 1
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 16
f14_instructionInterval: 5
f15_instructionGreater500: 0
f16_numOfEdges: 30
f17_numOfCriticalEdges: 4
f18_abnormalEdge: 0
f19_directCalls: 22
f20_condBranch: 6
f21_assigmentInstructions: 248
f22_uncondBranch: 12
f23_numOfIntOperations: 24
f24_numOfFloatOperations: 0
f25_numInstructions: 299
f26_instructionAverage: 14.2381
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 21
f30_blockPhiIntervalNodes: 21
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 2
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 4
f38_addresVar: 2
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 2
f42_oneOperandConst: 18
f43_callArgPtrType: 17
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 22
f47_constInt0: 22
f48_constInt32bits: 60
f49_constInt1: 9
f50_constInt64bits: 3
f51_numRefeOfLocalVar: 314
f52_defUseCounter: 29
f53_refLocalVariable: 233
f54_refExterVariable: 9
f55_localPtrVar: 93
f56_staticPtrVar: 0
