f01_totalBasicBlocks: 50
f02_oneSuccessor: 32
f03_twoSuccessor: 17
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 34
f06_twoPredecessor: 14
f07_greaterTwoPredecessor: 1
f08_onePredSuc: 28
f09_onePred_twoSuc: 6
f10_twoPred_oneSuc: 4
f11_twoPredSuc: 10
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 36
f14_instructionInterval: 14
f15_instructionGreater500: 0
f16_numOfEdges: 66
f17_numOfCriticalEdges: 6
f18_abnormalEdge: 0
f19_directCalls: 17
f20_condBranch: 17
f21_assigmentInstructions: 563
f22_uncondBranch: 32
f23_numOfIntOperations: 25
f24_numOfFloatOperations: 0
f25_numInstructions: 714
f26_instructionAverage: 14.28
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 50
f30_blockPhiIntervalNodes: 50
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 36
f38_addresVar: 33
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 15
f43_callArgPtrType: 7
f44_call4args: 0
f45_ptrRetCallType: 2
f46_intRetCallType: 15
f47_constInt0: 214
f48_constInt32bits: 343
f49_constInt1: 43
f50_constInt64bits: 8
f51_numRefeOfLocalVar: 796
f52_defUseCounter: 3
f53_refLocalVariable: 557
f54_refExterVariable: 3
f55_localPtrVar: 369
f56_staticPtrVar: 0
