f01_totalBasicBlocks: 47
f02_oneSuccessor: 24
f03_twoSuccessor: 22
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 29
f06_twoPredecessor: 16
f07_greaterTwoPredecessor: 1
f08_onePredSuc: 20
f09_onePred_twoSuc: 9
f10_twoPred_oneSuc: 4
f11_twoPredSuc: 12
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 42
f14_instructionInterval: 5
f15_instructionGreater500: 0
f16_numOfEdges: 68
f17_numOfCriticalEdges: 15
f18_abnormalEdge: 0
f19_directCalls: 3
f20_condBranch: 22
f21_assigmentInstructions: 307
f22_uncondBranch: 24
f23_numOfIntOperations: 25
f24_numOfFloatOperations: 0
f25_numInstructions: 391
f26_instructionAverage: 8.319149
f27_averagePhi: 0.04255319
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 45
f30_blockPhiIntervalNodes: 47
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 2
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 7
f38_addresVar: 3
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 10
f42_oneOperandConst: 14
f43_callArgPtrType: 3
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 3
f47_constInt0: 158
f48_constInt32bits: 216
f49_constInt1: 37
f50_constInt64bits: 24
f51_numRefeOfLocalVar: 381
f52_defUseCounter: 26
f53_refLocalVariable: 307
f54_refExterVariable: 14
f55_localPtrVar: 191
f56_staticPtrVar: 0
