f01_totalBasicBlocks: 50
f02_oneSuccessor: 27
f03_twoSuccessor: 22
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 29
f06_twoPredecessor: 18
f07_greaterTwoPredecessor: 2
f08_onePredSuc: 17
f09_onePred_twoSuc: 12
f10_twoPred_oneSuc: 9
f11_twoPredSuc: 8
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 44
f14_instructionInterval: 6
f15_instructionGreater500: 0
f16_numOfEdges: 71
f17_numOfCriticalEdges: 15
f18_abnormalEdge: 0
f19_directCalls: 1
f20_condBranch: 22
f21_assigmentInstructions: 233
f22_uncondBranch: 27
f23_numOfIntOperations: 1
f24_numOfFloatOperations: 0
f25_numInstructions: 320
f26_instructionAverage: 6.4
f27_averagePhi: 0.02
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 49
f30_blockPhiIntervalNodes: 50
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 1
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 4
f38_addresVar: 3
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 1
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 1
f47_constInt0: 106
f48_constInt32bits: 168
f49_constInt1: 12
f50_constInt64bits: 9
f51_numRefeOfLocalVar: 303
f52_defUseCounter: 22
f53_refLocalVariable: 232
f54_refExterVariable: 13
f55_localPtrVar: 149
f56_staticPtrVar: 9
