f01_totalBasicBlocks: 55
f02_oneSuccessor: 29
f03_twoSuccessor: 24
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 32
f06_twoPredecessor: 18
f07_greaterTwoPredecessor: 4
f08_onePredSuc: 16
f09_onePred_twoSuc: 15
f10_twoPred_oneSuc: 12
f11_twoPredSuc: 6
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 46
f14_instructionInterval: 9
f15_instructionGreater500: 0
f16_numOfEdges: 80
f17_numOfCriticalEdges: 20
f18_abnormalEdge: 0
f19_directCalls: 30
f20_condBranch: 23
f21_assigmentInstructions: 351
f22_uncondBranch: 29
f23_numOfIntOperations: 14
f24_numOfFloatOperations: 0
f25_numInstructions: 461
f26_instructionAverage: 8.381818
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 55
f30_blockPhiIntervalNodes: 55
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 2
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 12
f38_addresVar: 9
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 2
f42_oneOperandConst: 5
f43_callArgPtrType: 24
f44_call4args: 11
f45_ptrRetCallType: 6
f46_intRetCallType: 24
f47_constInt0: 100
f48_constInt32bits: 157
f49_constInt1: 14
f50_constInt64bits: 7
f51_numRefeOfLocalVar: 500
f52_defUseCounter: 18
f53_refLocalVariable: 342
f54_refExterVariable: 11
f55_localPtrVar: 175
f56_staticPtrVar: 0
