f01_totalBasicBlocks: 56
f02_oneSuccessor: 31
f03_twoSuccessor: 23
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 38
f06_twoPredecessor: 13
f07_greaterTwoPredecessor: 4
f08_onePredSuc: 27
f09_onePred_twoSuc: 11
f10_twoPred_oneSuc: 2
f11_twoPredSuc: 9
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 48
f14_instructionInterval: 8
f15_instructionGreater500: 0
f16_numOfEdges: 81
f17_numOfCriticalEdges: 13
f18_abnormalEdge: 0
f19_directCalls: 54
f20_condBranch: 23
f21_assigmentInstructions: 333
f22_uncondBranch: 31
f23_numOfIntOperations: 24
f24_numOfFloatOperations: 0
f25_numInstructions: 443
f26_instructionAverage: 7.910714
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 56
f30_blockPhiIntervalNodes: 56
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 15
f38_addresVar: 11
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 5
f42_oneOperandConst: 11
f43_callArgPtrType: 31
f44_call4args: 8
f45_ptrRetCallType: 6
f46_intRetCallType: 48
f47_constInt0: 108
f48_constInt32bits: 125
f49_constInt1: 15
f50_constInt64bits: 23
f51_numRefeOfLocalVar: 462
f52_defUseCounter: 27
f53_refLocalVariable: 320
f54_refExterVariable: 19
f55_localPtrVar: 136
f56_staticPtrVar: 3
