f01_totalBasicBlocks: 66
f02_oneSuccessor: 33
f03_twoSuccessor: 30
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 37
f06_twoPredecessor: 28
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 28
f09_onePred_twoSuc: 8
f10_twoPred_oneSuc: 4
f11_twoPredSuc: 22
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 64
f14_instructionInterval: 2
f15_instructionGreater500: 0
f16_numOfEdges: 93
f17_numOfCriticalEdges: 24
f18_abnormalEdge: 0
f19_directCalls: 47
f20_condBranch: 30
f21_assigmentInstructions: 212
f22_uncondBranch: 33
f23_numOfIntOperations: 2
f24_numOfFloatOperations: 0
f25_numInstructions: 309
f26_instructionAverage: 4.681818
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 66
f30_blockPhiIntervalNodes: 66
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 10
f38_addresVar: 8
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 4
f42_oneOperandConst: 1
f43_callArgPtrType: 32
f44_call4args: 8
f45_ptrRetCallType: 6
f46_intRetCallType: 41
f47_constInt0: 24
f48_constInt32bits: 30
f49_constInt1: 11
f50_constInt64bits: 10
f51_numRefeOfLocalVar: 267
f52_defUseCounter: 43
f53_refLocalVariable: 182
f54_refExterVariable: 23
f55_localPtrVar: 57
f56_staticPtrVar: 12
