f01_totalBasicBlocks: 25
f02_oneSuccessor: 14
f03_twoSuccessor: 10
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 14
f06_twoPredecessor: 10
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 7
f09_onePred_twoSuc: 7
f10_twoPred_oneSuc: 7
f11_twoPredSuc: 2
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 20
f14_instructionInterval: 5
f15_instructionGreater500: 0
f16_numOfEdges: 34
f17_numOfCriticalEdges: 6
f18_abnormalEdge: 0
f19_directCalls: 10
f20_condBranch: 10
f21_assigmentInstructions: 264
f22_uncondBranch: 14
f23_numOfIntOperations: 36
f24_numOfFloatOperations: 0
f25_numInstructions: 312
f26_instructionAverage: 12.48
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 25
f30_blockPhiIntervalNodes: 25
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 4
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 18
f42_oneOperandConst: 23
f43_callArgPtrType: 6
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 10
f47_constInt0: 78
f48_constInt32bits: 111
f49_constInt1: 21
f50_constInt64bits: 15
f51_numRefeOfLocalVar: 304
f52_defUseCounter: 16
f53_refLocalVariable: 256
f54_refExterVariable: 2
f55_localPtrVar: 100
f56_staticPtrVar: 14
