f01_totalBasicBlocks: 142
f02_oneSuccessor: 63
f03_twoSuccessor: 76
f04_greaterTwoSuccessor: 2
f05_onePredecessor: 86
f06_twoPredecessor: 37
f07_greaterTwoPredecessor: 18
f08_onePredSuc: 42
f09_onePred_twoSuc: 43
f10_twoPred_oneSuc: 16
f11_twoPredSuc: 19
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 124
f14_instructionInterval: 18
f15_instructionGreater500: 0
f16_numOfEdges: 223
f17_numOfCriticalEdges: 74
f18_abnormalEdge: 0
f19_directCalls: 35
f20_condBranch: 76
f21_assigmentInstructions: 879
f22_uncondBranch: 63
f23_numOfIntOperations: 62
f24_numOfFloatOperations: 0
f25_numInstructions: 1107
f26_instructionAverage: 7.795774
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 142
f30_blockPhiIntervalNodes: 142
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 2
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 4
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 3
f42_oneOperandConst: 49
f43_callArgPtrType: 24
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 35
f47_constInt0: 289
f48_constInt32bits: 468
f49_constInt1: 58
f50_constInt64bits: 65
f51_numRefeOfLocalVar: 1062
f52_defUseCounter: 81
f53_refLocalVariable: 850
f54_refExterVariable: 4
f55_localPtrVar: 497
f56_staticPtrVar: 79
