f01_totalBasicBlocks: 115
f02_oneSuccessor: 66
f03_twoSuccessor: 48
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 66
f06_twoPredecessor: 48
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 36
f09_onePred_twoSuc: 30
f10_twoPred_oneSuc: 30
f11_twoPredSuc: 17
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 94
f14_instructionInterval: 21
f15_instructionGreater500: 0
f16_numOfEdges: 162
f17_numOfCriticalEdges: 32
f18_abnormalEdge: 0
f19_directCalls: 188
f20_condBranch: 48
f21_assigmentInstructions: 908
f22_uncondBranch: 66
f23_numOfIntOperations: 60
f24_numOfFloatOperations: 0
f25_numInstructions: 1066
f26_instructionAverage: 9.269566
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 115
f30_blockPhiIntervalNodes: 115
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 5
f38_addresVar: 3
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 1
f42_oneOperandConst: 10
f43_callArgPtrType: 16
f44_call4args: 0
f45_ptrRetCallType: 2
f46_intRetCallType: 186
f47_constInt0: 253
f48_constInt32bits: 237
f49_constInt1: 43
f50_constInt64bits: 137
f51_numRefeOfLocalVar: 1105
f52_defUseCounter: 80
f53_refLocalVariable: 795
f54_refExterVariable: 66
f55_localPtrVar: 248
f56_staticPtrVar: 0
