f01_totalBasicBlocks: 170
f02_oneSuccessor: 97
f03_twoSuccessor: 72
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 123
f06_twoPredecessor: 42
f07_greaterTwoPredecessor: 4
f08_onePredSuc: 71
f09_onePred_twoSuc: 52
f10_twoPred_oneSuc: 25
f11_twoPredSuc: 17
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 128
f14_instructionInterval: 42
f15_instructionGreater500: 0
f16_numOfEdges: 241
f17_numOfCriticalEdges: 29
f18_abnormalEdge: 0
f19_directCalls: 113
f20_condBranch: 72
f21_assigmentInstructions: 1247
f22_uncondBranch: 97
f23_numOfIntOperations: 91
f24_numOfFloatOperations: 0
f25_numInstructions: 1642
f26_instructionAverage: 9.658824
f27_averagePhi: 0.005882353
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 169
f30_blockPhiIntervalNodes: 170
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 1
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 63
f38_addresVar: 53
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 13
f42_oneOperandConst: 72
f43_callArgPtrType: 104
f44_call4args: 0
f45_ptrRetCallType: 19
f46_intRetCallType: 94
f47_constInt0: 375
f48_constInt32bits: 627
f49_constInt1: 98
f50_constInt64bits: 36
f51_numRefeOfLocalVar: 1821
f52_defUseCounter: 56
f53_refLocalVariable: 1197
f54_refExterVariable: 29
f55_localPtrVar: 684
f56_staticPtrVar: 0
