f01_totalBasicBlocks: 72
f02_oneSuccessor: 39
f03_twoSuccessor: 32
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 43
f06_twoPredecessor: 24
f07_greaterTwoPredecessor: 4
f08_onePredSuc: 28
f09_onePred_twoSuc: 15
f10_twoPred_oneSuc: 8
f11_twoPredSuc: 15
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 59
f14_instructionInterval: 13
f15_instructionGreater500: 0
f16_numOfEdges: 103
f17_numOfCriticalEdges: 23
f18_abnormalEdge: 0
f19_directCalls: 46
f20_condBranch: 32
f21_assigmentInstructions: 568
f22_uncondBranch: 39
f23_numOfIntOperations: 14
f24_numOfFloatOperations: 0
f25_numInstructions: 724
f26_instructionAverage: 10.05556
f27_averagePhi: 0.04166667
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 69
f30_blockPhiIntervalNodes: 72
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 3
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 44
f38_addresVar: 36
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 9
f42_oneOperandConst: 8
f43_callArgPtrType: 24
f44_call4args: 1
f45_ptrRetCallType: 19
f46_intRetCallType: 25
f47_constInt0: 192
f48_constInt32bits: 274
f49_constInt1: 43
f50_constInt64bits: 20
f51_numRefeOfLocalVar: 739
f52_defUseCounter: 33
f53_refLocalVariable: 552
f54_refExterVariable: 20
f55_localPtrVar: 356
f56_staticPtrVar: 0
