f01_totalBasicBlocks: 40
f02_oneSuccessor: 24
f03_twoSuccessor: 14
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 26
f06_twoPredecessor: 10
f07_greaterTwoPredecessor: 3
f08_onePredSuc: 20
f09_onePred_twoSuc: 6
f10_twoPred_oneSuc: 3
f11_twoPredSuc: 6
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 33
f14_instructionInterval: 7
f15_instructionGreater500: 0
f16_numOfEdges: 58
f17_numOfCriticalEdges: 8
f18_abnormalEdge: 0
f19_directCalls: 37
f20_condBranch: 14
f21_assigmentInstructions: 560
f22_uncondBranch: 24
f23_numOfIntOperations: 97
f24_numOfFloatOperations: 0
f25_numInstructions: 670
f26_instructionAverage: 16.75
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 40
f30_blockPhiIntervalNodes: 40
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 2
f38_addresVar: 1
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 2
f42_oneOperandConst: 32
f43_callArgPtrType: 29
f44_call4args: 2
f45_ptrRetCallType: 1
f46_intRetCallType: 36
f47_constInt0: 140
f48_constInt32bits: 279
f49_constInt1: 23
f50_constInt64bits: 8
f51_numRefeOfLocalVar: 729
f52_defUseCounter: 73
f53_refLocalVariable: 536
f54_refExterVariable: 68
f55_localPtrVar: 222
f56_staticPtrVar: 0
