f01_totalBasicBlocks: 68
f02_oneSuccessor: 33
f03_twoSuccessor: 34
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 51
f06_twoPredecessor: 10
f07_greaterTwoPredecessor: 6
f08_onePredSuc: 27
f09_onePred_twoSuc: 24
f10_twoPred_oneSuc: 2
f11_twoPredSuc: 8
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 62
f14_instructionInterval: 6
f15_instructionGreater500: 0
f16_numOfEdges: 101
f17_numOfCriticalEdges: 18
f18_abnormalEdge: 0
f19_directCalls: 19
f20_condBranch: 34
f21_assigmentInstructions: 398
f22_uncondBranch: 33
f23_numOfIntOperations: 20
f24_numOfFloatOperations: 0
f25_numInstructions: 514
f26_instructionAverage: 7.558824
f27_averagePhi: 0.01470588
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 67
f30_blockPhiIntervalNodes: 68
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 1
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 11
f38_addresVar: 8
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 9
f42_oneOperandConst: 20
f43_callArgPtrType: 13
f44_call4args: 3
f45_ptrRetCallType: 2
f46_intRetCallType: 17
f47_constInt0: 148
f48_constInt32bits: 218
f49_constInt1: 31
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 532
f52_defUseCounter: 16
f53_refLocalVariable: 391
f54_refExterVariable: 9
f55_localPtrVar: 208
f56_staticPtrVar: 4
