f01_totalBasicBlocks: 16
f02_oneSuccessor: 9
f03_twoSuccessor: 6
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 10
f06_twoPredecessor: 4
f07_greaterTwoPredecessor: 1
f08_onePredSuc: 7
f09_onePred_twoSuc: 3
f10_twoPred_oneSuc: 2
f11_twoPredSuc: 2
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 13
f14_instructionInterval: 3
f15_instructionGreater500: 0
f16_numOfEdges: 21
f17_numOfCriticalEdges: 3
f18_abnormalEdge: 0
f19_directCalls: 46
f20_condBranch: 6
f21_assigmentInstructions: 293
f22_uncondBranch: 9
f23_numOfIntOperations: 13
f24_numOfFloatOperations: 0
f25_numInstructions: 315
f26_instructionAverage: 19.6875
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 16
f30_blockPhiIntervalNodes: 16
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 0
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 3
f42_oneOperandConst: 12
f43_callArgPtrType: 9
f44_call4args: 0
f45_ptrRetCallType: 1
f46_intRetCallType: 45
f47_constInt0: 137
f48_constInt32bits: 263
f49_constInt1: 38
f50_constInt64bits: 2
f51_numRefeOfLocalVar: 336
f52_defUseCounter: 3
f53_refLocalVariable: 249
f54_refExterVariable: 3
f55_localPtrVar: 130
f56_staticPtrVar: 1
