f01_totalBasicBlocks: 79
f02_oneSuccessor: 46
f03_twoSuccessor: 32
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 55
f06_twoPredecessor: 22
f07_greaterTwoPredecessor: 1
f08_onePredSuc: 33
f09_onePred_twoSuc: 22
f10_twoPred_oneSuc: 12
f11_twoPredSuc: 10
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 76
f14_instructionInterval: 3
f15_instructionGreater500: 0
f16_numOfEdges: 110
f17_numOfCriticalEdges: 12
f18_abnormalEdge: 0
f19_directCalls: 25
f20_condBranch: 32
f21_assigmentInstructions: 300
f22_uncondBranch: 46
f23_numOfIntOperations: 14
f24_numOfFloatOperations: 0
f25_numInstructions: 413
f26_instructionAverage: 5.227848
f27_averagePhi: 0.113924
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 70
f30_blockPhiIntervalNodes: 79
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 9
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 5
f38_addresVar: 3
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 10
f42_oneOperandConst: 13
f43_callArgPtrType: 24
f44_call4args: 6
f45_ptrRetCallType: 1
f46_intRetCallType: 24
f47_constInt0: 102
f48_constInt32bits: 129
f49_constInt1: 24
f50_constInt64bits: 7
f51_numRefeOfLocalVar: 421
f52_defUseCounter: 25
f53_refLocalVariable: 289
f54_refExterVariable: 14
f55_localPtrVar: 119
f56_staticPtrVar: 0
