f01_totalBasicBlocks: 10
f02_oneSuccessor: 6
f03_twoSuccessor: 3
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 6
f06_twoPredecessor: 3
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 5
f09_onePred_twoSuc: 1
f10_twoPred_oneSuc: 1
f11_twoPredSuc: 1
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 5
f14_instructionInterval: 5
f15_instructionGreater500: 0
f16_numOfEdges: 12
f17_numOfCriticalEdges: 0
f18_abnormalEdge: 0
f19_directCalls: 60
f20_condBranch: 3
f21_assigmentInstructions: 278
f22_uncondBranch: 6
f23_numOfIntOperations: 0
f24_numOfFloatOperations: 0
f25_numInstructions: 348
f26_instructionAverage: 34.8
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 10
f30_blockPhiIntervalNodes: 10
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 24
f38_addresVar: 22
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 0
f43_callArgPtrType: 17
f44_call4args: 0
f45_ptrRetCallType: 13
f46_intRetCallType: 47
f47_constInt0: 66
f48_constInt32bits: 120
f49_constInt1: 36
f50_constInt64bits: 6
f51_numRefeOfLocalVar: 373
f52_defUseCounter: 13
f53_refLocalVariable: 261
f54_refExterVariable: 7
f55_localPtrVar: 171
f56_staticPtrVar: 9
