f01_totalBasicBlocks: 95
f02_oneSuccessor: 43
f03_twoSuccessor: 50
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 65
f06_twoPredecessor: 14
f07_greaterTwoPredecessor: 15
f08_onePredSuc: 25
f09_onePred_twoSuc: 40
f10_twoPred_oneSuc: 11
f11_twoPredSuc: 3
f12_greaterTwoPredSuc: 1
f13_instructionLess15: 93
f14_instructionInterval: 2
f15_instructionGreater500: 0
f16_numOfEdges: 177
f17_numOfCriticalEdges: 69
f18_abnormalEdge: 0
f19_directCalls: 2
f20_condBranch: 50
f21_assigmentInstructions: 168
f22_uncondBranch: 43
f23_numOfIntOperations: 18
f24_numOfFloatOperations: 0
f25_numInstructions: 295
f26_instructionAverage: 3.105263
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 95
f30_blockPhiIntervalNodes: 95
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 7
f38_addresVar: 2
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 3
f43_callArgPtrType: 2
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 2
f47_constInt0: 29
f48_constInt32bits: 26
f49_constInt1: 9
f50_constInt64bits: 78
f51_numRefeOfLocalVar: 249
f52_defUseCounter: 20
f53_refLocalVariable: 167
f54_refExterVariable: 16
f55_localPtrVar: 20
f56_staticPtrVar: 0
