f01_totalBasicBlocks: 50
f02_oneSuccessor: 31
f03_twoSuccessor: 18
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 31
f06_twoPredecessor: 18
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 25
f09_onePred_twoSuc: 6
f10_twoPred_oneSuc: 6
f11_twoPredSuc: 11
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 32
f14_instructionInterval: 18
f15_instructionGreater500: 0
f16_numOfEdges: 67
f17_numOfCriticalEdges: 6
f18_abnormalEdge: 0
f19_directCalls: 12
f20_condBranch: 18
f21_assigmentInstructions: 615
f22_uncondBranch: 31
f23_numOfIntOperations: 60
f24_numOfFloatOperations: 0
f25_numInstructions: 763
f26_instructionAverage: 15.26
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 50
f30_blockPhiIntervalNodes: 50
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 1
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 1
f42_oneOperandConst: 48
f43_callArgPtrType: 11
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 12
f47_constInt0: 276
f48_constInt32bits: 402
f49_constInt1: 55
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 815
f52_defUseCounter: 60
f53_refLocalVariable: 604
f54_refExterVariable: 39
f55_localPtrVar: 301
f56_staticPtrVar: 0
