f01_totalBasicBlocks: 96
f02_oneSuccessor: 56
f03_twoSuccessor: 35
f04_greaterTwoSuccessor: 4
f05_onePredecessor: 58
f06_twoPredecessor: 31
f07_greaterTwoPredecessor: 6
f08_onePredSuc: 48
f09_onePred_twoSuc: 6
f10_twoPred_oneSuc: 4
f11_twoPredSuc: 26
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 95
f14_instructionInterval: 1
f15_instructionGreater500: 0
f16_numOfEdges: 149
f17_numOfCriticalEdges: 35
f18_abnormalEdge: 0
f19_directCalls: 83
f20_condBranch: 35
f21_assigmentInstructions: 422
f22_uncondBranch: 56
f23_numOfIntOperations: 0
f24_numOfFloatOperations: 1
f25_numInstructions: 549
f26_instructionAverage: 5.71875
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 96
f30_blockPhiIntervalNodes: 96
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 4
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 0
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 0
f43_callArgPtrType: 81
f44_call4args: 0
f45_ptrRetCallType: 2
f46_intRetCallType: 81
f47_constInt0: 88
f48_constInt32bits: 68
f49_constInt1: 2
f50_constInt64bits: 37
f51_numRefeOfLocalVar: 465
f52_defUseCounter: 33
f53_refLocalVariable: 354
f54_refExterVariable: 32
f55_localPtrVar: 83
f56_staticPtrVar: 1
