f01_totalBasicBlocks: 87
f02_oneSuccessor: 53
f03_twoSuccessor: 31
f04_greaterTwoSuccessor: 2
f05_onePredecessor: 49
f06_twoPredecessor: 37
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 40
f09_onePred_twoSuc: 9
f10_twoPred_oneSuc: 13
f11_twoPredSuc: 21
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 80
f14_instructionInterval: 7
f15_instructionGreater500: 0
f16_numOfEdges: 123
f17_numOfCriticalEdges: 21
f18_abnormalEdge: 0
f19_directCalls: 128
f20_condBranch: 31
f21_assigmentInstructions: 487
f22_uncondBranch: 53
f23_numOfIntOperations: 17
f24_numOfFloatOperations: 0
f25_numInstructions: 621
f26_instructionAverage: 7.137931
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 87
f30_blockPhiIntervalNodes: 87
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 2
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 5
f38_addresVar: 1
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 14
f43_callArgPtrType: 124
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 128
f47_constInt0: 103
f48_constInt32bits: 289
f49_constInt1: 37
f50_constInt64bits: 4
f51_numRefeOfLocalVar: 624
f52_defUseCounter: 58
f53_refLocalVariable: 388
f54_refExterVariable: 37
f55_localPtrVar: 179
f56_staticPtrVar: 0
