f01_totalBasicBlocks: 112
f02_oneSuccessor: 60
f03_twoSuccessor: 51
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 71
f06_twoPredecessor: 35
f07_greaterTwoPredecessor: 5
f08_onePredSuc: 35
f09_onePred_twoSuc: 35
f10_twoPred_oneSuc: 23
f11_twoPredSuc: 12
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 101
f14_instructionInterval: 11
f15_instructionGreater500: 0
f16_numOfEdges: 162
f17_numOfCriticalEdges: 33
f18_abnormalEdge: 0
f19_directCalls: 10
f20_condBranch: 51
f21_assigmentInstructions: 747
f22_uncondBranch: 60
f23_numOfIntOperations: 8
f24_numOfFloatOperations: 34
f25_numInstructions: 932
f26_instructionAverage: 8.321428
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 112
f30_blockPhiIntervalNodes: 112
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 1
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 4
f42_oneOperandConst: 8
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 9
f47_constInt0: 215
f48_constInt32bits: 303
f49_constInt1: 33
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 976
f52_defUseCounter: 40
f53_refLocalVariable: 747
f54_refExterVariable: 15
f55_localPtrVar: 353
f56_staticPtrVar: 0
