f01_totalBasicBlocks: 90
f02_oneSuccessor: 52
f03_twoSuccessor: 37
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 52
f06_twoPredecessor: 37
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 41
f09_onePred_twoSuc: 11
f10_twoPred_oneSuc: 11
f11_twoPredSuc: 25
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 83
f14_instructionInterval: 7
f15_instructionGreater500: 0
f16_numOfEdges: 126
f17_numOfCriticalEdges: 22
f18_abnormalEdge: 0
f19_directCalls: 143
f20_condBranch: 37
f21_assigmentInstructions: 461
f22_uncondBranch: 52
f23_numOfIntOperations: 23
f24_numOfFloatOperations: 0
f25_numInstructions: 557
f26_instructionAverage: 6.188889
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 90
f30_blockPhiIntervalNodes: 90
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 2
f38_addresVar: 1
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 13
f43_callArgPtrType: 139
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 143
f47_constInt0: 85
f48_constInt32bits: 201
f49_constInt1: 39
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 403
f52_defUseCounter: 42
f53_refLocalVariable: 318
f54_refExterVariable: 36
f55_localPtrVar: 153
f56_staticPtrVar: 0
