f01_totalBasicBlocks: 34
f02_oneSuccessor: 23
f03_twoSuccessor: 10
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 23
f06_twoPredecessor: 10
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 19
f09_onePred_twoSuc: 4
f10_twoPred_oneSuc: 4
f11_twoPredSuc: 5
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 29
f14_instructionInterval: 5
f15_instructionGreater500: 0
f16_numOfEdges: 43
f17_numOfCriticalEdges: 1
f18_abnormalEdge: 0
f19_directCalls: 23
f20_condBranch: 10
f21_assigmentInstructions: 222
f22_uncondBranch: 23
f23_numOfIntOperations: 12
f24_numOfFloatOperations: 0
f25_numInstructions: 278
f26_instructionAverage: 8.176471
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 34
f30_blockPhiIntervalNodes: 34
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 8
f38_addresVar: 6
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 4
f42_oneOperandConst: 12
f43_callArgPtrType: 18
f44_call4args: 4
f45_ptrRetCallType: 3
f46_intRetCallType: 20
f47_constInt0: 13
f48_constInt32bits: 30
f49_constInt1: 15
f50_constInt64bits: 2
f51_numRefeOfLocalVar: 282
f52_defUseCounter: 38
f53_refLocalVariable: 202
f54_refExterVariable: 15
f55_localPtrVar: 77
f56_staticPtrVar: 4
