f01_totalBasicBlocks: 77
f02_oneSuccessor: 31
f03_twoSuccessor: 45
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 49
f06_twoPredecessor: 19
f07_greaterTwoPredecessor: 8
f08_onePredSuc: 19
f09_onePred_twoSuc: 30
f10_twoPred_oneSuc: 10
f11_twoPredSuc: 9
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 75
f14_instructionInterval: 2
f15_instructionGreater500: 0
f16_numOfEdges: 121
f17_numOfCriticalEdges: 43
f18_abnormalEdge: 0
f19_directCalls: 25
f20_condBranch: 45
f21_assigmentInstructions: 202
f22_uncondBranch: 31
f23_numOfIntOperations: 11
f24_numOfFloatOperations: 0
f25_numInstructions: 313
f26_instructionAverage: 4.064935
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 77
f30_blockPhiIntervalNodes: 77
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 19
f38_addresVar: 11
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 0
f43_callArgPtrType: 23
f44_call4args: 0
f45_ptrRetCallType: 7
f46_intRetCallType: 18
f47_constInt0: 47
f48_constInt32bits: 52
f49_constInt1: 5
f50_constInt64bits: 7
f51_numRefeOfLocalVar: 275
f52_defUseCounter: 15
f53_refLocalVariable: 192
f54_refExterVariable: 8
f55_localPtrVar: 91
f56_staticPtrVar: 1
