f01_totalBasicBlocks: 9
f02_oneSuccessor: 5
f03_twoSuccessor: 2
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 5
f06_twoPredecessor: 2
f07_greaterTwoPredecessor: 1
f08_onePredSuc: 4
f09_onePred_twoSuc: 1
f10_twoPred_oneSuc: 1
f11_twoPredSuc: 0
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 3
f14_instructionInterval: 6
f15_instructionGreater500: 0
f16_numOfEdges: 12
f17_numOfCriticalEdges: 2
f18_abnormalEdge: 0
f19_directCalls: 13
f20_condBranch: 2
f21_assigmentInstructions: 185
f22_uncondBranch: 5
f23_numOfIntOperations: 1
f24_numOfFloatOperations: 0
f25_numInstructions: 261
f26_instructionAverage: 29.0
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 9
f30_blockPhiIntervalNodes: 9
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 32
f38_addresVar: 30
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 2
f42_oneOperandConst: 1
f43_callArgPtrType: 9
f44_call4args: 1
f45_ptrRetCallType: 0
f46_intRetCallType: 13
f47_constInt0: 54
f48_constInt32bits: 107
f49_constInt1: 28
f50_constInt64bits: 13
f51_numRefeOfLocalVar: 289
f52_defUseCounter: 17
f53_refLocalVariable: 178
f54_refExterVariable: 14
f55_localPtrVar: 141
f56_staticPtrVar: 10
