f01_totalBasicBlocks: 154
f02_oneSuccessor: 60
f03_twoSuccessor: 91
f04_greaterTwoSuccessor: 2
f05_onePredecessor: 102
f06_twoPredecessor: 34
f07_greaterTwoPredecessor: 17
f08_onePredSuc: 35
f09_onePred_twoSuc: 65
f10_twoPred_oneSuc: 19
f11_twoPredSuc: 15
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 151
f14_instructionInterval: 3
f15_instructionGreater500: 0
f16_numOfEdges: 248
f17_numOfCriticalEdges: 91
f18_abnormalEdge: 0
f19_directCalls: 79
f20_condBranch: 91
f21_assigmentInstructions: 417
f22_uncondBranch: 60
f23_numOfIntOperations: 0
f24_numOfFloatOperations: 0
f25_numInstructions: 651
f26_instructionAverage: 4.227273
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 154
f30_blockPhiIntervalNodes: 154
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 2
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 1
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 0
f43_callArgPtrType: 0
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 79
f47_constInt0: 92
f48_constInt32bits: 108
f49_constInt1: 39
f50_constInt64bits: 30
f51_numRefeOfLocalVar: 598
f52_defUseCounter: 77
f53_refLocalVariable: 417
f54_refExterVariable: 28
f55_localPtrVar: 46
f56_staticPtrVar: 5
