f01_totalBasicBlocks: 108
f02_oneSuccessor: 70
f03_twoSuccessor: 36
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 85
f06_twoPredecessor: 19
f07_greaterTwoPredecessor: 3
f08_onePredSuc: 61
f09_onePred_twoSuc: 23
f10_twoPred_oneSuc: 6
f11_twoPredSuc: 13
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 95
f14_instructionInterval: 13
f15_instructionGreater500: 0
f16_numOfEdges: 147
f17_numOfCriticalEdges: 4
f18_abnormalEdge: 0
f19_directCalls: 52
f20_condBranch: 36
f21_assigmentInstructions: 520
f22_uncondBranch: 70
f23_numOfIntOperations: 25
f24_numOfFloatOperations: 0
f25_numInstructions: 727
f26_instructionAverage: 6.731482
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 108
f30_blockPhiIntervalNodes: 108
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 24
f38_addresVar: 19
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 12
f42_oneOperandConst: 25
f43_callArgPtrType: 47
f44_call4args: 0
f45_ptrRetCallType: 4
f46_intRetCallType: 48
f47_constInt0: 119
f48_constInt32bits: 213
f49_constInt1: 29
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 726
f52_defUseCounter: 32
f53_refLocalVariable: 479
f54_refExterVariable: 13
f55_localPtrVar: 239
f56_staticPtrVar: 6
