f01_totalBasicBlocks: 32
f02_oneSuccessor: 17
f03_twoSuccessor: 14
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 22
f06_twoPredecessor: 8
f07_greaterTwoPredecessor: 1
f08_onePredSuc: 13
f09_onePred_twoSuc: 9
f10_twoPred_oneSuc: 4
f11_twoPredSuc: 4
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 28
f14_instructionInterval: 4
f15_instructionGreater500: 0
f16_numOfEdges: 45
f17_numOfCriticalEdges: 6
f18_abnormalEdge: 0
f19_directCalls: 6
f20_condBranch: 14
f21_assigmentInstructions: 214
f22_uncondBranch: 17
f23_numOfIntOperations: 21
f24_numOfFloatOperations: 0
f25_numInstructions: 272
f26_instructionAverage: 8.5
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 32
f30_blockPhiIntervalNodes: 32
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 4
f38_addresVar: 2
f39_addressFunction: 0
f40_indirectCalls: 4
f41_leftOpIntConst: 7
f42_oneOperandConst: 8
f43_callArgPtrType: 5
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 9
f47_constInt0: 95
f48_constInt32bits: 127
f49_constInt1: 18
f50_constInt64bits: 3
f51_numRefeOfLocalVar: 269
f52_defUseCounter: 23
f53_refLocalVariable: 206
f54_refExterVariable: 17
f55_localPtrVar: 118
f56_staticPtrVar: 0
