f01_totalBasicBlocks: 16
f02_oneSuccessor: 10
f03_twoSuccessor: 5
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 10
f06_twoPredecessor: 5
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 6
f09_onePred_twoSuc: 4
f10_twoPred_oneSuc: 4
f11_twoPredSuc: 0
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 14
f14_instructionInterval: 2
f15_instructionGreater500: 0
f16_numOfEdges: 20
f17_numOfCriticalEdges: 0
f18_abnormalEdge: 0
f19_directCalls: 29
f20_condBranch: 5
f21_assigmentInstructions: 212
f22_uncondBranch: 10
f23_numOfIntOperations: 0
f24_numOfFloatOperations: 0
f25_numInstructions: 276
f26_instructionAverage: 17.25
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 16
f30_blockPhiIntervalNodes: 16
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 42
f38_addresVar: 39
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 0
f43_callArgPtrType: 28
f44_call4args: 23
f45_ptrRetCallType: 22
f46_intRetCallType: 7
f47_constInt0: 66
f48_constInt32bits: 114
f49_constInt1: 4
f50_constInt64bits: 6
f51_numRefeOfLocalVar: 299
f52_defUseCounter: 18
f53_refLocalVariable: 210
f54_refExterVariable: 6
f55_localPtrVar: 172
f56_staticPtrVar: 16
