f01_totalBasicBlocks: 41
f02_oneSuccessor: 27
f03_twoSuccessor: 13
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 27
f06_twoPredecessor: 13
f07_greaterTwoPredecessor: 0
f08_onePredSuc: 21
f09_onePred_twoSuc: 5
f10_twoPred_oneSuc: 6
f11_twoPredSuc: 7
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 29
f14_instructionInterval: 12
f15_instructionGreater500: 0
f16_numOfEdges: 53
f17_numOfCriticalEdges: 2
f18_abnormalEdge: 0
f19_directCalls: 164
f20_condBranch: 13
f21_assigmentInstructions: 586
f22_uncondBranch: 27
f23_numOfIntOperations: 107
f24_numOfFloatOperations: 0
f25_numInstructions: 640
f26_instructionAverage: 15.60976
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 41
f30_blockPhiIntervalNodes: 41
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 7
f38_addresVar: 6
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 99
f42_oneOperandConst: 27
f43_callArgPtrType: 65
f44_call4args: 4
f45_ptrRetCallType: 7
f46_intRetCallType: 157
f47_constInt0: 89
f48_constInt32bits: 260
f49_constInt1: 37
f50_constInt64bits: 10
f51_numRefeOfLocalVar: 653
f52_defUseCounter: 80
f53_refLocalVariable: 529
f54_refExterVariable: 28
f55_localPtrVar: 174
f56_staticPtrVar: 0
