f01_totalBasicBlocks: 153
f02_oneSuccessor: 101
f03_twoSuccessor: 48
f04_greaterTwoSuccessor: 3
f05_onePredecessor: 101
f06_twoPredecessor: 48
f07_greaterTwoPredecessor: 3
f08_onePredSuc: 58
f09_onePred_twoSuc: 40
f10_twoPred_oneSuc: 40
f11_twoPredSuc: 7
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 147
f14_instructionInterval: 6
f15_instructionGreater500: 0
f16_numOfEdges: 208
f17_numOfCriticalEdges: 7
f18_abnormalEdge: 0
f19_directCalls: 76
f20_condBranch: 48
f21_assigmentInstructions: 632
f22_uncondBranch: 101
f23_numOfIntOperations: 17
f24_numOfFloatOperations: 0
f25_numInstructions: 875
f26_instructionAverage: 5.718954
f27_averagePhi: 0.09150327
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 139
f30_blockPhiIntervalNodes: 153
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 14
f34_numOfSwitchInstruction: 3
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 37
f38_addresVar: 35
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 12
f42_oneOperandConst: 8
f43_callArgPtrType: 68
f44_call4args: 0
f45_ptrRetCallType: 9
f46_intRetCallType: 67
f47_constInt0: 185
f48_constInt32bits: 342
f49_constInt1: 41
f50_constInt64bits: 30
f51_numRefeOfLocalVar: 824
f52_defUseCounter: 58
f53_refLocalVariable: 594
f54_refExterVariable: 27
f55_localPtrVar: 340
f56_staticPtrVar: 3
