f01_totalBasicBlocks: 95
f02_oneSuccessor: 48
f03_twoSuccessor: 44
f04_greaterTwoSuccessor: 2
f05_onePredecessor: 57
f06_twoPredecessor: 28
f07_greaterTwoPredecessor: 9
f08_onePredSuc: 33
f09_onePred_twoSuc: 22
f10_twoPred_oneSuc: 11
f11_twoPredSuc: 16
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 93
f14_instructionInterval: 2
f15_instructionGreater500: 0
f16_numOfEdges: 148
f17_numOfCriticalEdges: 43
f18_abnormalEdge: 0
f19_directCalls: 30
f20_condBranch: 44
f21_assigmentInstructions: 291
f22_uncondBranch: 48
f23_numOfIntOperations: 4
f24_numOfFloatOperations: 0
f25_numInstructions: 433
f26_instructionAverage: 4.557895
f27_averagePhi: 0.07368421
f28_averagePhiArgs: 2.142857
f29_blockWithoutPhi: 88
f30_blockPhiIntervalNodes: 95
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 7
f34_numOfSwitchInstruction: 2
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 31
f38_addresVar: 25
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 6
f42_oneOperandConst: 4
f43_callArgPtrType: 19
f44_call4args: 3
f45_ptrRetCallType: 7
f46_intRetCallType: 23
f47_constInt0: 57
f48_constInt32bits: 69
f49_constInt1: 21
f50_constInt64bits: 11
f51_numRefeOfLocalVar: 406
f52_defUseCounter: 18
f53_refLocalVariable: 279
f54_refExterVariable: 13
f55_localPtrVar: 147
f56_staticPtrVar: 2
