f01_totalBasicBlocks: 135
f02_oneSuccessor: 63
f03_twoSuccessor: 71
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 84
f06_twoPredecessor: 48
f07_greaterTwoPredecessor: 2
f08_onePredSuc: 46
f09_onePred_twoSuc: 38
f10_twoPred_oneSuc: 16
f11_twoPredSuc: 32
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 132
f14_instructionInterval: 3
f15_instructionGreater500: 0
f16_numOfEdges: 205
f17_numOfCriticalEdges: 63
f18_abnormalEdge: 0
f19_directCalls: 46
f20_condBranch: 71
f21_assigmentInstructions: 491
f22_uncondBranch: 63
f23_numOfIntOperations: 46
f24_numOfFloatOperations: 0
f25_numInstructions: 685
f26_instructionAverage: 5.074074
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 135
f30_blockPhiIntervalNodes: 135
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 28
f38_addresVar: 26
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 11
f43_callArgPtrType: 44
f44_call4args: 0
f45_ptrRetCallType: 15
f46_intRetCallType: 31
f47_constInt0: 144
f48_constInt32bits: 182
f49_constInt1: 19
f50_constInt64bits: 4
f51_numRefeOfLocalVar: 663
f52_defUseCounter: 37
f53_refLocalVariable: 462
f54_refExterVariable: 10
f55_localPtrVar: 216
f56_staticPtrVar: 0
