f01_totalBasicBlocks: 133
f02_oneSuccessor: 72
f03_twoSuccessor: 60
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 89
f06_twoPredecessor: 36
f07_greaterTwoPredecessor: 7
f08_onePredSuc: 44
f09_onePred_twoSuc: 45
f10_twoPred_oneSuc: 23
f11_twoPredSuc: 13
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 120
f14_instructionInterval: 13
f15_instructionGreater500: 0
f16_numOfEdges: 192
f17_numOfCriticalEdges: 35
f18_abnormalEdge: 0
f19_directCalls: 51
f20_condBranch: 60
f21_assigmentInstructions: 553
f22_uncondBranch: 72
f23_numOfIntOperations: 13
f24_numOfFloatOperations: 0
f25_numInstructions: 735
f26_instructionAverage: 5.526316
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 133
f30_blockPhiIntervalNodes: 133
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 13
f38_addresVar: 7
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 3
f43_callArgPtrType: 42
f44_call4args: 0
f45_ptrRetCallType: 2
f46_intRetCallType: 48
f47_constInt0: 235
f48_constInt32bits: 309
f49_constInt1: 18
f50_constInt64bits: 22
f51_numRefeOfLocalVar: 705
f52_defUseCounter: 47
f53_refLocalVariable: 536
f54_refExterVariable: 22
f55_localPtrVar: 271
f56_staticPtrVar: 0
