f01_totalBasicBlocks: 53
f02_oneSuccessor: 31
f03_twoSuccessor: 20
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 33
f06_twoPredecessor: 16
f07_greaterTwoPredecessor: 3
f08_onePredSuc: 17
f09_onePred_twoSuc: 15
f10_twoPred_oneSuc: 10
f11_twoPredSuc: 5
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 48
f14_instructionInterval: 5
f15_instructionGreater500: 0
f16_numOfEdges: 75
f17_numOfCriticalEdges: 12
f18_abnormalEdge: 0
f19_directCalls: 31
f20_condBranch: 19
f21_assigmentInstructions: 286
f22_uncondBranch: 31
f23_numOfIntOperations: 8
f24_numOfFloatOperations: 0
f25_numInstructions: 356
f26_instructionAverage: 6.716981
f27_averagePhi: 0.09433962
f28_averagePhiArgs: 2.0
f29_blockWithoutPhi: 48
f30_blockPhiIntervalNodes: 53
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 5
f34_numOfSwitchInstruction: 2
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 7
f38_addresVar: 3
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 4
f42_oneOperandConst: 5
f43_callArgPtrType: 26
f44_call4args: 4
f45_ptrRetCallType: 4
f46_intRetCallType: 26
f47_constInt0: 77
f48_constInt32bits: 101
f49_constInt1: 13
f50_constInt64bits: 40
f51_numRefeOfLocalVar: 362
f52_defUseCounter: 23
f53_refLocalVariable: 268
f54_refExterVariable: 4
f55_localPtrVar: 148
f56_staticPtrVar: 0
