f01_totalBasicBlocks: 183
f02_oneSuccessor: 86
f03_twoSuccessor: 95
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 130
f06_twoPredecessor: 35
f07_greaterTwoPredecessor: 17
f08_onePredSuc: 67
f09_onePred_twoSuc: 62
f10_twoPred_oneSuc: 14
f11_twoPredSuc: 21
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 179
f14_instructionInterval: 4
f15_instructionGreater500: 0
f16_numOfEdges: 281
f17_numOfCriticalEdges: 68
f18_abnormalEdge: 0
f19_directCalls: 66
f20_condBranch: 95
f21_assigmentInstructions: 572
f22_uncondBranch: 86
f23_numOfIntOperations: 27
f24_numOfFloatOperations: 0
f25_numInstructions: 893
f26_instructionAverage: 4.879781
f27_averagePhi: 0.03278688
f28_averagePhiArgs: 2.666667
f29_blockWithoutPhi: 177
f30_blockPhiIntervalNodes: 183
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 6
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 12
f38_addresVar: 7
f39_addressFunction: 0
f40_indirectCalls: 3
f41_leftOpIntConst: 4
f42_oneOperandConst: 18
f43_callArgPtrType: 26
f44_call4args: 0
f45_ptrRetCallType: 5
f46_intRetCallType: 63
f47_constInt0: 174
f48_constInt32bits: 156
f49_constInt1: 74
f50_constInt64bits: 137
f51_numRefeOfLocalVar: 879
f52_defUseCounter: 19
f53_refLocalVariable: 543
f54_refExterVariable: 11
f55_localPtrVar: 134
f56_staticPtrVar: 0
