f01_totalBasicBlocks: 48
f02_oneSuccessor: 31
f03_twoSuccessor: 14
f04_greaterTwoSuccessor: 2
f05_onePredecessor: 36
f06_twoPredecessor: 7
f07_greaterTwoPredecessor: 4
f08_onePredSuc: 27
f09_onePred_twoSuc: 8
f10_twoPred_oneSuc: 2
f11_twoPredSuc: 4
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 42
f14_instructionInterval: 6
f15_instructionGreater500: 0
f16_numOfEdges: 70
f17_numOfCriticalEdges: 8
f18_abnormalEdge: 0
f19_directCalls: 41
f20_condBranch: 14
f21_assigmentInstructions: 430
f22_uncondBranch: 31
f23_numOfIntOperations: 84
f24_numOfFloatOperations: 0
f25_numInstructions: 531
f26_instructionAverage: 11.0625
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 48
f30_blockPhiIntervalNodes: 48
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 2
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 4
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 17
f42_oneOperandConst: 29
f43_callArgPtrType: 7
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 41
f47_constInt0: 95
f48_constInt32bits: 134
f49_constInt1: 31
f50_constInt64bits: 16
f51_numRefeOfLocalVar: 499
f52_defUseCounter: 104
f53_refLocalVariable: 392
f54_refExterVariable: 19
f55_localPtrVar: 118
f56_staticPtrVar: 34
