f01_totalBasicBlocks: 51
f02_oneSuccessor: 22
f03_twoSuccessor: 27
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 38
f06_twoPredecessor: 7
f07_greaterTwoPredecessor: 5
f08_onePredSuc: 20
f09_onePred_twoSuc: 18
f10_twoPred_oneSuc: 1
f11_twoPredSuc: 5
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 50
f14_instructionInterval: 1
f15_instructionGreater500: 0
f16_numOfEdges: 79
f17_numOfCriticalEdges: 19
f18_abnormalEdge: 0
f19_directCalls: 3
f20_condBranch: 27
f21_assigmentInstructions: 204
f22_uncondBranch: 22
f23_numOfIntOperations: 21
f24_numOfFloatOperations: 0
f25_numInstructions: 281
f26_instructionAverage: 5.509804
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 51
f30_blockPhiIntervalNodes: 51
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 2
f38_addresVar: 0
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 13
f42_oneOperandConst: 14
f43_callArgPtrType: 3
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 3
f47_constInt0: 64
f48_constInt32bits: 102
f49_constInt1: 6
f50_constInt64bits: 2
f51_numRefeOfLocalVar: 262
f52_defUseCounter: 35
f53_refLocalVariable: 200
f54_refExterVariable: 19
f55_localPtrVar: 78
f56_staticPtrVar: 0
