f01_totalBasicBlocks: 47
f02_oneSuccessor: 31
f03_twoSuccessor: 12
f04_greaterTwoSuccessor: 3
f05_onePredecessor: 23
f06_twoPredecessor: 15
f07_greaterTwoPredecessor: 8
f08_onePredSuc: 20
f09_onePred_twoSuc: 2
f10_twoPred_oneSuc: 5
f11_twoPredSuc: 8
f12_greaterTwoPredSuc: 1
f13_instructionLess15: 36
f14_instructionInterval: 11
f15_instructionGreater500: 0
f16_numOfEdges: 91
f17_numOfCriticalEdges: 37
f18_abnormalEdge: 0
f19_directCalls: 5
f20_condBranch: 12
f21_assigmentInstructions: 281
f22_uncondBranch: 31
f23_numOfIntOperations: 38
f24_numOfFloatOperations: 0
f25_numInstructions: 377
f26_instructionAverage: 8.021276
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 47
f30_blockPhiIntervalNodes: 47
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 3
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 13
f38_addresVar: 11
f39_addressFunction: 0
f40_indirectCalls: 2
f41_leftOpIntConst: 0
f42_oneOperandConst: 9
f43_callArgPtrType: 5
f44_call4args: 0
f45_ptrRetCallType: 1
f46_intRetCallType: 6
f47_constInt0: 94
f48_constInt32bits: 188
f49_constInt1: 17
f50_constInt64bits: 0
f51_numRefeOfLocalVar: 374
f52_defUseCounter: 45
f53_refLocalVariable: 275
f54_refExterVariable: 24
f55_localPtrVar: 145
f56_staticPtrVar: 9
