f01_totalBasicBlocks: 139
f02_oneSuccessor: 73
f03_twoSuccessor: 63
f04_greaterTwoSuccessor: 2
f05_onePredecessor: 97
f06_twoPredecessor: 15
f07_greaterTwoPredecessor: 26
f08_onePredSuc: 66
f09_onePred_twoSuc: 30
f10_twoPred_oneSuc: 0
f11_twoPredSuc: 14
f12_greaterTwoPredSuc: 1
f13_instructionLess15: 126
f14_instructionInterval: 13
f15_instructionGreater500: 0
f16_numOfEdges: 211
f17_numOfCriticalEdges: 53
f18_abnormalEdge: 0
f19_directCalls: 3
f20_condBranch: 63
f21_assigmentInstructions: 1057
f22_uncondBranch: 73
f23_numOfIntOperations: 12
f24_numOfFloatOperations: 0
f25_numInstructions: 1404
f26_instructionAverage: 10.10072
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 139
f30_blockPhiIntervalNodes: 139
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 2
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 155
f38_addresVar: 154
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 12
f43_callArgPtrType: 3
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 3
f47_constInt0: 514
f48_constInt32bits: 928
f49_constInt1: 127
f50_constInt64bits: 31
f51_numRefeOfLocalVar: 1226
f52_defUseCounter: 298
f53_refLocalVariable: 1054
f54_refExterVariable: 9
f55_localPtrVar: 917
f56_staticPtrVar: 298
