f01_totalBasicBlocks: 29
f02_oneSuccessor: 17
f03_twoSuccessor: 11
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 19
f06_twoPredecessor: 8
f07_greaterTwoPredecessor: 1
f08_onePredSuc: 13
f09_onePred_twoSuc: 6
f10_twoPred_oneSuc: 3
f11_twoPredSuc: 5
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 24
f14_instructionInterval: 5
f15_instructionGreater500: 0
f16_numOfEdges: 39
f17_numOfCriticalEdges: 6
f18_abnormalEdge: 0
f19_directCalls: 4
f20_condBranch: 11
f21_assigmentInstructions: 207
f22_uncondBranch: 17
f23_numOfIntOperations: 5
f24_numOfFloatOperations: 0
f25_numInstructions: 264
f26_instructionAverage: 9.103448
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 29
f30_blockPhiIntervalNodes: 29
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 13
f38_addresVar: 12
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 2
f42_oneOperandConst: 5
f43_callArgPtrType: 2
f44_call4args: 1
f45_ptrRetCallType: 3
f46_intRetCallType: 1
f47_constInt0: 65
f48_constInt32bits: 83
f49_constInt1: 20
f50_constInt64bits: 8
f51_numRefeOfLocalVar: 283
f52_defUseCounter: 14
f53_refLocalVariable: 206
f54_refExterVariable: 10
f55_localPtrVar: 128
f56_staticPtrVar: 0
