f01_totalBasicBlocks: 76
f02_oneSuccessor: 34
f03_twoSuccessor: 41
f04_greaterTwoSuccessor: 0
f05_onePredecessor: 53
f06_twoPredecessor: 15
f07_greaterTwoPredecessor: 7
f08_onePredSuc: 22
f09_onePred_twoSuc: 31
f10_twoPred_oneSuc: 9
f11_twoPredSuc: 6
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 74
f14_instructionInterval: 2
f15_instructionGreater500: 0
f16_numOfEdges: 116
f17_numOfCriticalEdges: 29
f18_abnormalEdge: 0
f19_directCalls: 26
f20_condBranch: 41
f21_assigmentInstructions: 322
f22_uncondBranch: 34
f23_numOfIntOperations: 23
f24_numOfFloatOperations: 0
f25_numInstructions: 437
f26_instructionAverage: 5.75
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 76
f30_blockPhiIntervalNodes: 76
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 0
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 13
f38_addresVar: 12
f39_addressFunction: 0
f40_indirectCalls: 5
f41_leftOpIntConst: 0
f42_oneOperandConst: 0
f43_callArgPtrType: 26
f44_call4args: 0
f45_ptrRetCallType: 0
f46_intRetCallType: 31
f47_constInt0: 114
f48_constInt32bits: 119
f49_constInt1: 25
f50_constInt64bits: 22
f51_numRefeOfLocalVar: 410
f52_defUseCounter: 53
f53_refLocalVariable: 304
f54_refExterVariable: 25
f55_localPtrVar: 129
f56_staticPtrVar: 9
