f01_totalBasicBlocks: 134
f02_oneSuccessor: 77
f03_twoSuccessor: 55
f04_greaterTwoSuccessor: 1
f05_onePredecessor: 91
f06_twoPredecessor: 37
f07_greaterTwoPredecessor: 5
f08_onePredSuc: 45
f09_onePred_twoSuc: 46
f10_twoPred_oneSuc: 29
f11_twoPredSuc: 6
f12_greaterTwoPredSuc: 0
f13_instructionLess15: 118
f14_instructionInterval: 16
f15_instructionGreater500: 0
f16_numOfEdges: 218
f17_numOfCriticalEdges: 51
f18_abnormalEdge: 0
f19_directCalls: 63
f20_condBranch: 55
f21_assigmentInstructions: 883
f22_uncondBranch: 77
f23_numOfIntOperations: 75
f24_numOfFloatOperations: 0
f25_numInstructions: 1138
f26_instructionAverage: 8.492537
f27_averagePhi: 0.0
f28_averagePhiArgs: 0.0
f29_blockWithoutPhi: 134
f30_blockPhiIntervalNodes: 134
f31_blockPhiGreater3Nodes: 0
f32_blocksPhiGreater5Arg: 0
f33_blocksPhiIntervalArg: 0
f34_numOfSwitchInstruction: 1
f35_numOfUnaryOperations: 0
f36_ptrArithmetic: 0
f37_indirectRefs: 29
f38_addresVar: 26
f39_addressFunction: 0
f40_indirectCalls: 0
f41_leftOpIntConst: 0
f42_oneOperandConst: 70
f43_callArgPtrType: 58
f44_call4args: 0
f45_ptrRetCallType: 22
f46_intRetCallType: 41
f47_constInt0: 180
f48_constInt32bits: 438
f49_constInt1: 106
f50_constInt64bits: 39
f51_numRefeOfLocalVar: 1194
f52_defUseCounter: 3
f53_refLocalVariable: 846
f54_refExterVariable: 3
f55_localPtrVar: 488
f56_staticPtrVar: 0
